# Generated by Django 6.0.4 on 2026-05-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_message_options_conversation_last_message_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="model",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="usage",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
