# Generated by Django 6.0.4 on 2026-05-10 14:52

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_message_provider_userapikey"),
    ]

    operations = [
        VectorExtension(),
    ]
