# Generated by Django 6.0.4 on 2026-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_document_documentchunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
