# Generated by Django 6.0.4 on 2026-05-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_document_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="meta",
        ),
        migrations.AddField(
            model_name="message",
            name="compacted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_compaction_summary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="raw_question",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai", "OpenAI"),
                    ("llamacpp", "llama.cpp"),
                    ("anthropic", "Anthropic"),
                    ("google", "Google"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userapikey",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("llamacpp", "llama.cpp"),
                    ("anthropic", "Anthropic"),
                    ("google", "Google"),
                ],
                max_length=32,
            ),
        ),
    ]
