# Generated by Django 6.0.4 on 2026-05-19 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_restructure_message_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="meta",
        ),
    ]
