# Generated by Django 6.0.4 on 2026-05-21 10:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_conversation_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="language",
            field=models.CharField(
                choices=[("english", "English"), ("polish", "Polish")],
                default="english",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="word_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="chunk_search_vector_idx"
            ),
        ),
    ]
