# Generated by Django 6.0.4 on 2026-05-25 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_hybrid_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="GetDocsJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "github_repo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("english", "English"), ("polish", "Polish")],
                        default="english",
                        max_length=16,
                    ),
                ),
                ("pages_fetched", models.PositiveIntegerField(default=0)),
                ("pages_total", models.PositiveIntegerField(blank=True, null=True)),
                ("max_pages", models.PositiveIntegerField(default=150)),
                ("max_depth", models.PositiveIntegerField(default=3)),
                ("delay_seconds", models.FloatField(default=1.5)),
                ("timeout", models.FloatField(default=15.0)),
                ("skip_llms_full", models.BooleanField(default=False)),
                ("fair_use", models.BooleanField(default=True)),
                (
                    "source_method",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="get_docs_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
