# Generated by Django 6.0.4 on 2026-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_getdocsjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
