# Generated by Django 6.0.4 on 2026-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_document_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getdocsjob",
            name="job_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
