# Generated by Django 6.0.4 on 2026-06-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_getdocsjob_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="truncated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="compacted",
            field=models.BooleanField(default=False),
        ),
    ]
