# Generated by Django 6.0.4 on 2026-06-12 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_message_truncated_alter_message_compacted"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=127)),
                ("saved_path", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.message",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
