# Generated by Django 6.0.4 on 2026-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapikey",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("llamacpp", "llama.cpp"),
                    ("anthropic", "Anthropic"),
                    ("gemini", "Gemini"),
                ],
                max_length=32,
            ),
        ),
    ]
