# Generated by Django 6.0.4 on 2026-06-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_userapikey_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapikey",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("llamacpp", "llama.cpp"),
                    ("openrouter", "OpenRouter"),
                    ("gemini", "Gemini"),
                    ("github", "GitHub"),
                ],
                max_length=32,
            ),
        ),
    ]
