# Generated by Django 6.0.4 on 2026-06-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_message_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="mode",
            field=models.CharField(
                choices=[("direct", "Direct"), ("side-by-side", "Side-by-Side")],
                default="direct",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="variant",
            field=models.CharField(
                blank=True,
                choices=[("rag_on", "RAG On"), ("rag_off", "RAG Off")],
                max_length=16,
                null=True,
            ),
        ),
    ]
