# Generated by Django 6.0.4 on 2026-06-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_conversation_mode_message_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai", "OpenAI"),
                    ("llamacpp", "llama.cpp"),
                    ("openrouter", "OpenRouter"),
                    ("gemini", "Gemini"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
