# Generated by Django 6.0.4 on 2026-06-13 15:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("raw_text", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[("english", "English"), ("polish", "Polish")],
                        default="english",
                        max_length=16,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("source_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GetDocsJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_id", models.CharField(max_length=255, null=True, unique=True)),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "github_repo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("english", "English"), ("polish", "Polish")],
                        default="english",
                        max_length=16,
                    ),
                ),
                ("pages_fetched", models.PositiveIntegerField(default=0)),
                ("pages_total", models.PositiveIntegerField(blank=True, null=True)),
                ("max_pages", models.PositiveIntegerField(default=150)),
                ("max_depth", models.PositiveIntegerField(default=3)),
                ("delay_seconds", models.FloatField(default=1.5)),
                ("timeout", models.FloatField(default=15.0)),
                ("skip_llms_full", models.BooleanField(default=False)),
                ("fair_use", models.BooleanField(default=True)),
                (
                    "source_method",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="get_docs_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("chunk_index", models.PositiveIntegerField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="documents_d_documen_8ea6ce_idx",
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="chunk_embedding_idx",
                        opclasses=["vector_cosine_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="chunk_search_vector_idx"
                    ),
                ],
            },
        ),
    ]
