# Generated by Django 6.0.4 on 2026-06-18 10:34

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_polish_fts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
