# Generated by Django 6.0.4 on 2026-06-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_alter_documentchunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
