# Generated by Django 6.0.4 on 2026-06-28 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_document_error_message_document_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("parent_index", models.PositiveIntegerField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["parent_index"],
            },
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="parent_chunk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_chunks",
                to="documents.parentchunk",
            ),
        ),
        migrations.AddIndex(
            model_name="parentchunk",
            index=models.Index(
                fields=["document", "parent_index"],
                name="documents_p_documen_6dd5bb_idx",
            ),
        ),
    ]
